spring:
  profiles:
    active: local
  datasource:
    url: jdbc:h2:tcp://localhost/~/jpa-shop
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
        use_sql_comments: true

logging.level:
  org.hibernate.SQL: debug
